[package]
name = "needle-searcher"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
indicatif = "0.17.8"
multiversion = "0.7.4"
rayon = "1.10.0"
smallvec = "1.13.2"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"